title: Patrick A. Fletcher
author: Patrick A. Fletcher
email: patrick.allen.fletcher@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  #Postdoc at the Laboratory of Biological Modeling

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://patrickfletcher.github.io" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  patrickfletcher

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

permalink: pretty
